# Generated by Django 3.0.3 on 2020-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='notA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marksheet',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='topic_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='total_q',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marksheet',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
