# Generated by Django 3.0.3 on 2020-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200502_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
