# Generated by Django 3.0.3 on 2020-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200503_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
