# Generated by Django 3.0.3 on 2020-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_topic_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tpq',
            field=models.IntegerField(default=25),
        ),
    ]
