# Generated by Django 3.0.3 on 2020-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_topic_tpq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tpq',
            field=models.IntegerField(default=15),
        ),
    ]
