# Generated by Django 3.0.3 on 2020-05-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_objection_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
