# Generated by Django 3.0.3 on 2020-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_objection_dateofreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='right_ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='user_ans',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
